my_app/urls.py
from django.conf.urls import url
from my_app import views

app_name="my_app"

urlpatterns=[
    url(r'^$',views.PostListView.as_view(),name="post_list"),
    url(r'^about/$',views.AboutView.as_view(),name="about"),
    url(r'^post/(?P<pk>\d+)$',views.PostDetailView.as_view(),name="post_detail"),
    url(r'post/create/$',views.CreatePost,name="create_post"),
    url(r'^post/(?P<pk>\d+)/update$',views.UpdatePostView.as_view(),name="update_post"),
    url(r'^post/(?P<pk>\d+)/delete$',views.DeletePostView.as_view(),name="delete_post"),
    url(r'^draft/$',views.DraftPostView.as_view(),name="draft_post"),
    url(r'^post/(?P<pk>\d+)/publish/$',views.publish_post,name="publish_post"),
    url(r'^post/(?P<pk>\d+)/comment$',views.add_comment,name="comment_post"),
    url(r'^comment/(?P<pk>\d+)/update$',views.UpdateCommentView.as_view(),name="update_comment"),
    url(r'^comment/(?P<pk>\d+)/delete$',views.comment_remove,name="delete_comment"),
    url(r'^post/(?P<pk>\d+)/commentlist$',views.CommentListView.as_view(),name="comment_list"),
    url(r'^register/$',views.reg,name="register"),
    url(r'^accounts/profile/$',views.profile,name="profile"),
    url(r'^profile/$',views.ProfileView.as_view(),name="user_profile"),
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$',views.get_user_profile,name="get_user_profile"),
    url(r'^post/(?P<pk>\d+)/apply/$',views.Apply,name="apply"),
    url(r'^mentor/$',views.get_mentors,name="mentor_list"),
]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import views


urlpatterns = [
    url('admin/', admin.site.urls),
    # url(r'^user/', include('my_app.urls')),
    url(r'',include('my_app.urls')),
    #url(r'^register$',views.reg,name="register"),
    url(r'^login/$', views.LoginView, name='login'),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
]

my_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.



class Post(models.Model):
    title=models.CharField(max_length=256)
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    text=models.TextField()
    create_date=models.DateTimeField(default=timezone.now)
    publish_date=models.DateTimeField(blank=True,null=True)

    def get_absolute_url(self):
        return reverse('my_app:post_list')


    def publish(self):
        print("hey")
        self.publish_date=timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post=models.ForeignKey('Post',related_name="Comment",on_delete=models.CASCADE)
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    text=models.TextField()
    create_date=models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return str(self.author)


    def get_absolute_url(self):
        return reverse('my_app:post_list',kwargs={'pk':self.post.pk})


CHOICES = (
    ('mentor','MENTOR'),
    ('student', 'STUDENT'),
)

class User_info(models.Model):
    username=models.OneToOneField(User,on_delete=models.CASCADE)
    profilepic=models.ImageField(blank=True,upload_to='profilePic')
    type_of_user=models.CharField(max_length=250,choices=CHOICES,default='student')
    facebook = models.CharField(max_length=50, default='facebook login')
    
    def __str__(self):
        return self.username.username

class Pairing(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    mentor = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    money = models.IntegerField(default = 0)
    Ack1 = models.BooleanField(default = True)
    Ack2 = models.BooleanField(default = False)
    Ack3 = models.BooleanField(default = False)
    Ack4 = models.BooleanField(default = False)
    
    def __str__(self):
        return str(self.mentor)

my_app/forms.py
from django import forms
from my_app.models import Post,Comment,User_info
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=('title','text')

        widgets = {
            'title': forms.Textarea(attrs={
                'class': 'editable medium-editor-textarea postcontent form-control',
                'rows': '2'
                }),
            'text': forms.Textarea(attrs={
                'class': 'editable medium-editor-textarea postcontent form-control',
                'rows': '4'
                }),
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model=Comment
        exclude=('post','author','create_date')

        widgets = {
    
            'text': forms.Textarea(attrs={
                'class': 'editable medium-editor-textarea',
                'rows': '2',
                'cols': '18'
                }),
        }


class UserForm(forms.ModelForm):

    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':' register'}))
    class Meta():
        model=User
        fields=('username','password','email')

class UserProfileForm(forms.ModelForm):
    facebook=forms.CharField(widget=forms.TextInput(attrs={
        'class':'register'
    }))
    class Meta():
        model=User_info
        fields=('profilepic','type_of_user','facebook')

my_app/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView,ListView,DetailView,CreateView,DetailView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy,reverse
from my_app.models import Post,Comment,User_info,Pairing
from my_app.forms import PostForm,CommentForm,UserForm,UserProfileForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.utils import timezone

from django.shortcuts import render

# Create your views here.

class AboutView(TemplateView):
    template_name='About.html'
 
class PostListView(ListView):
    model=Post
    def get_queryset(self):
        return Post.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')
    

class PostDetailView(DetailView):
    model=Post
   

# class CreatePostView(LoginRequiredMixin,CreateView):
    
#     login_url='/login/'
#     redirect_field_name='my_app/post_detail.html'
#     form_class=PostForm
#     model=Post
#     context_object_name='post'

@login_required
def CreatePost(request):
    if(request.method=="POST"):
        print(request.POST)
        form=PostForm(data=request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.title = post.title
            post.author=request.user
            post.save()
            return redirect('my_app:post_detail',pk=post.pk)
        else:
            return HttpResponse("invalid information")
    else:
        form=PostForm()
    return render(request,'post_form.html',{'form':form})
    

class UpdatePostView(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name='my_app/post_detail.html'
    form_class=PostForm
    model=Post

@login_required
def Apply(request,pk):
    print(pk)
    print('something somrg')
    # model=Pairing
    # pairing=get_object_or_create(Pairing)
    post = Post.objects.get(pk = pk)
    pairing, boo = Pairing.objects.get_or_create(post=post, mentor=request.user)
    print(pairing)
    pairing.money = 5
    pairing.save()
    post_pk=pairing.post.pk
    # print(pairing.post)
    # pairing.save()
    return redirect('my_app:get_user_profile', username=pairing.mentor)
    # a href = "{% url 'my_app:get_user_profile' username=pairing.mentor %}"


class DeletePostView(LoginRequiredMixin,DeleteView):
    model=Post 
    success_url=reverse_lazy("my_app:post_list")


class DraftPostView(LoginRequiredMixin,ListView):
    model=Post
    login_url='/login/'
    redirect_field_name='my_app/post_detail.html'
    template_name="draft_post.html"
  

    def get_queryset(self):
      return Post.objects.filter(author=self.request.user)

    # def for_user(self, user):
    #     if user.is_authenticated():
    #         return self.get_query_set().filter(Post__author=user)
    #     else:
    #         return self.get_query_set().none()

   

@login_required
def publish_post(request,pk):
    post=get_object_or_404(Post,pk=pk)
    print(post.title)
    post.publish()
    return redirect('my_app:post_list')


@login_required
def add_comment(request,pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.author=request.user
            comment.save()
            return redirect('my_app:post_detail', pk=post.pk)
        else :
            HttpResponse("Invalid")
    else :
        form=CommentForm()
    return render(request,'comment_form.html',{'form':form,'post':post})

@login_required
def comment_remove(request,pk):
    comment=get_object_or_404(Comment,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('my_app:post_detail',pk=post_pk)

class UpdateCommentView(UpdateView,LoginRequiredMixin):
    login_url='/login/'
    redirect_field_name='my_app/post_detail.html'
    form_class=CommentForm
    model=Comment

class CommentListView(DetailView):
    model=Post
    template_name="comment_list.html"

def reg(request):
    registered=False
    if request.method=="POST":
        Userform=UserForm(data=request.POST)
        Profileform=UserProfileForm(data=request.POST)

        if Userform.is_valid() and Profileform.is_valid():
            user=Userform.save()
            user.set_password(user.password)
            user.save()

            profile=Profileform.save(commit=False)
            profile.username=user
            print(profile.type_of_user)

            # profile.type_of_user='type_of_user'
        
            profile.facebook=profile.facebook


            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            
            profile.save()
            registered=True
    
    else:
        Userform=UserForm()
        Profileform=UserProfileForm()
    return render(request,'form_page.html',{'Userform':Userform,'Profileform':Profileform,'registered':registered})


def profile(request):
    return redirect('my_app:post_list')



class ProfileView(ListView):
    model=Post 
    template_name="profile_list.html"
    


def get_user_profile(request, username):
    user = User.objects.get(username=username)
    post_list = Post.objects.all()
    return render(request, 'my_app/user_profile.html', {"user":user, "post_list":post_list})


def get_mentors(request):
    # user = User.objects.get(username=username)
    pairing_list = Pairing.objects.all()
    
    # final_id=idd[25:]
    # print(final_id)
    return render(request, 'my_app/pairing_list.html', { "pairing_list":pairing_list})

# class MentorList(ListView):
#     model=Pairing
#     template_name="pairing_list.html"

my_app/templates/my_app/About.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div class="techfont center blog ">
    <h1 class='commenttitle'>Welcome to my Blog</h1>
    <p id="aboutus">
        This is my first Django project where I tried to make a blog where any person could register and a logged in user 
        could post his ideas/stories and add comments to any of the posts.<br>
        It is a publishing platform where you can publish your stories and read other important facts and posts.
    </p>
</div>
{% endblock %}

my_app/templates/my_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <!-- bootstrap -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        font-awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <!-- Custom css -->
        <link rel="stylesheet" href="{% static 'css/main.css'%}">
        <!-- Google fonts -->
        <link href="https://fonts.googleapis.com/css?family=Sniglet" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
        <style type="text/css">
            * {
                font-family: 'Lato', sans-serif;
            }
        </style>

        <!-- <link href="https://fonts.googleapis.com/css?family=Armata|Russo+One|Wendy+One" rel="stylesheet">  -->
        <!-- MEDIUM STYLE EDITOR -->
        <!-- <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8"> -->
    </head>
    <body class="loader">

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #3c3c3c;">
      <a class="navbar-brand" href="#">Hadoop Daemons</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="form-inline my-2 my-lg-0">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'my_app:post_list' %}">Questions</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if user.is_authenticated %}
              {{ user | title }}
            {% else %}
              Join
            {% endif %}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'my_app:user_profile'  %}">Profile</a>
              <a class="dropdown-item" href="{% url 'my_app:draft_post' %}">Drafts</a>
              <a class="dropdown-item" href="{% url 'my_app:create_post' %}">New Post</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'login' %}">Login</a>
              <a class="dropdown-item" href="{% url 'my_app:register' %}">Register</a>
            {% endif %}
            </div>
          </li>
        </ul>
        </div>
      </div>
    </nav>        
        <div class="container ">
                {% block body_block %}
                {% endblock %}
        </div>
    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

my_app/templates/my_app/comment_form.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div id="commentform">
    <form method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-info btn-lg" id="commformsubbut"><b>Comment</b></button>
            
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
</div> 
{% endblock %}  

my_app/templates/my_app/comment_list.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div class="comments center post">
    <h1 class="commenttitle techfont">Comments :</h1>
       {% for comments in post.Comment.all %}
           <div><strong><a href = "{% url 'my_app:get_user_profile' username=comments.author %}">{{comments|title}}</a></strong>:{{comments.text|safe|linebreaksbr}}</div>
        {% endfor %}
</div>

{% endblock %}

my_app/templates/my_app/draft_post.html
{% extends 'my_app/base.html' %}
{% block body_block %}

<div>
    {% for posts in post_list %}
      {% if posts.publish_date %}
      <div class="card">
      <div class="card-header">
        <a href="{% url 'my_app:post_detail' pk=posts.pk %}"><b>{{posts.title|title}}</b></a>
      </div>
      <div class="card-body">
        <h5 class="card-title">{{posts.text|truncatewords:20|safe|linebreaksbr}}</h5>
        <p class="card-text">{{posts.author|title}}</p>
        <h5>{{posts.create_date}}</h5>
        <a  href="{% url 'my_app:update_post' pk=posts.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="delete" href="{% url 'my_app:delete_post' pk=posts.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=posts.pk %}">Publish</a>
      </div>
    </div>
    {% else %}
        {% endif %}

        {% endfor %}
</div>
<style type="text/css">
    .card {
        margin: 25px 0;
        opacity: 0.7;
        font-size: 30px;
        font-weight: 400;
    }
</style>

</div>

<!-- <div class="center">
        {% for posts in post_list %}
        {% if not posts.publish_date %}
        <div class="post">
                <p class ="posttitle"><a  href="{% url 'my_app:post_detail' pk=posts.pk %}"><b>{{posts.title|title}}</b></a></p>
                <div class="posttext">{{posts.text|truncatewords:20|safe|linebreaksbr}}</div><br>
                <h5><strong>{{posts.author|title}}</strong></h5>
                <h5>{{posts.create_date}}</h5>
                <a  href="{% url 'my_app:update_post' pk=posts.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="delete" href="{% url 'my_app:delete_post' pk=posts.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=posts.pk %}">Publish</a>
        </div>
        {% else %}
        {%endif%}
        {% endfor %}
</div> -->

{% endblock %}

my_app/templates/my_app/post_confirm_delete.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<!-- <div class="text-center">
       <form method="post">
           {% csrf_token %}
           <div id="deletemessage">
           <h4 id="deletetext">Are you sure that you want to delete <strong>{{object}}</strong>!</h4>
           <input type="submit" value="Confirm" class="btn btn-lg btn-danger">
           </div>
       </form> 
</div>  -->
<div class="center">
<div class="card text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><strong>Delete</strong></h5>
    <form method="post">
           {% csrf_token %}
    <!-- <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> -->
    <p class="card-text">Are you sure that you want to delete <strong>{{object}}</strong>? </p>
    <input type="submit" value="Confirm" class="btn btn-lg btn-danger">
    <a href="{% url 'my_app:post_list' %}" type="submit" value="Confirm" class="btn btn-lg btn-success">Cancel</a>
    </form> 
    <!-- <a href="#" class="card-link">Card link</a> -->
    <!-- <a href="#" class="card-link">Another link</a> -->
  </div>
</div>
</div>
<style type="text/css">
	.card{
		margin-top: 30%;
		margin-left: 10%;
	}
</style>
{% endblock %}  

my_app/templates/my_app/post_detail.html
{% extends 'my_app/base.html' %}
{% block body_block %}

<div class="post">
       <div class="posttitle"><a ><b>{{post.title|title}}</b></a></div>
       <p class='posttext' >{{ post.text|safe|linebreaksbr }}</p>
       <div><strong>{{post.author|title}}</strong></div>
       {% ifequal post.author user %}
       <a href="{% url 'my_app:update_post' pk=post.pk %}"><span class="fa fa-pencil-alt"></span></a>
       <a class="delete" href="{% url 'my_app:delete_post' pk=post.pk %}"><span class="fa fa-trash-alt"></span></a> 
        {% endifequal %}

       {% if post.publish_date %}
       <div class ="date">{{post.publish_date}}</div>
</div>

<!-- <div class="post">
    <div class="commenttitle"><b>{{post.Comment.all.count}} Comment</b></div>
        {% for comment in post.Comment.all %}
        <h5><strong>{{comment.author|title}}</strong>:{{comment.text|safe|linebreaksbr}}</h5>
        {% ifequal comment.author user %}
       <a href="{% url 'my_app:update_post' pk=post.pk %}"><span class="fa fa-pencil-alt"></span></a>
       <a class="delete" href="{% url 'my_app:delete_post' pk=post.pk %}"><span class="fa fa-trash-alt"></span></a> 
        {% endifequal %}
        {% endfor %} -->
<!-- </div> -->
       <!-- {% else %} -->
       <!-- <p>{{post.create_date}}</p> -->
       <!-- <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=post.pk %}">Publish</a> -->
<!-- </div> -->
       <!-- {% endif %} -->
<!-- </div> -->
<a  id="mentor" href= "{% url 'my_app:mentor_list' %}">Mentor List</a>
<style>
       #mentor{
              font-size: 2rem;
              color: aliceblue;
              margin-top:10%; 
       }

       .post{
              opacity: 0.65;
              border-radius:7%; 
       }
</style>
{% endblock %}  

my_app/templates/my_app/post_form.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div id="postform">
    <form  method="POST">
    	<div class="form-group">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-info btn-lg" value="Save" id="formsubbut"> Post </button>
        </div>
    </form>
    </div>
    <script>
         var editor = new MediumEditor('.editable');
         
       
    </script> 
{% endblock %}  

my_app/templates/my_app/post_list.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<div>
    {% for posts in post_list %}
      {% if posts.publish_date %}
      <div class="card">
      <div class="card-header">
        <a href="{% url 'my_app:post_detail' pk=posts.pk %}"><b>{{posts.title|title}}</b></a>
      </div>
      <div class="card-body">
        <h5 class="card-title">{{posts.text|truncatewords:20|safe|linebreaksbr}}</h5>
        <p class="card-text"><strong>Anonymous</strong></p>
        <div class="date">{{posts.publish_date}}</div>
        <div><a href="{% url 'my_app:comment_list' pk=posts.pk%}" >Comments:{{posts.Comment.all.count}}</a></div>
        {% ifequal posts.pk x %}
        <i class="fa fa-check-circle" style="font-size:48px;color:green"></i>
        {% else %}
        <a class="btn btn-info comment-btn" href="{% url 'my_app:apply' pk=posts.pk %}">Apply</a>
        {% endifequal %}
        </div>
      </div>
        {% endif %}

        {% endfor %}
</div>
<style type="text/css">
    .card {
        margin: 25px 0;
        opacity: 0.7;
        font-size: 30px;
        font-weight: 400;
    }
</style>

{% endblock %}

my_app/templates/my_app/profile_list.html
{% extends 'my_app/base.html' %}
{% load staticfiles%}
{% block body_block %}
<h1 class='commenttitle techfont' id="heading">Welcome {{user|title}}!!</h1><br>           
        {% for posts in post_list %}
           {% ifequal posts.author user %}
           <div class="card">
            <div class="card-header">
              <a href="{% url 'my_app:post_detail' pk=posts.pk %}"><b>{{posts.title|title}}</b></a>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{posts.text|truncatewords:20|safe|linebreaksbr}}</h5>
              <p class="card-text"><strong>{{posts.author|title}}</strong></p>
              <a href="{% url 'my_app:comment_post' pk=posts.pk %}" class="btn btn-primary">Apply</a>
              {% if posts.publish_date %}
               <div class="date">{{posts.publish_date}}</div>
               {% ifnotequal posts.author user %}    
               <a class="btn btn-info comment-btn" href="{% url 'my_app:comment_post' pk=posts.pk %}">Add Comment</a>
               {% endifnotequal %} 
               {% ifequal posts.author user %}
               <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=posts.pk %}">Publish</a>
               {% endifequal %}
               {% else %}
              <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=posts.pk %}">Publish</a>
              {% endif %}
               <div><a href="{% url 'my_app:comment_list' pk=posts.pk%}" >Comments:{{posts.Comment.all.count}}</a></div>
            </div>
            </div>
            {% else %}
            {% endifequal %}
            {% endfor %}           
          <style type="text/css">
    .card {
        margin: 25px 0;
        opacity: 0.7;
        font-size: 30px;
        font-weight: 400;
    }
    #heading{
        color: white;
        font-size: 70px;
        font-weight: 500;
        margin-top:30%;
    }
</style>
<script>
  username = document.getElementsByClassName('.techfont')[0];

</script>
{% endblock %}  

my_app/templates/my_app/user_profile.html
{% extends 'my_app/base.html' %}
{% load staticfiles%}
{% block body_block %}
<h1 class='commenttitle techfont' id="heading">Welcome {{user|title}}!!</h1><br>
This is big boss
           
        {% for posts in post_list %}
           {% ifequal posts.author user %}
           <div class="card">
            <div class="card-header">
              <a href="{% url 'my_app:post_detail' pk=posts.pk %}"><b>{{posts.title|title}}</b></a>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{posts.text|truncatewords:20|safe|linebreaksbr}}</h5>
              <p class="card-text"><strong>{{posts.author|title}}</strong></p>
              <a href="{% url 'my_app:comment_post' pk=posts.pk %}" class="btn btn-primary">Apply</a>
              {% if posts.publish_date %}
               <div class="date">{{posts.publish_date}}</div>
               <a class="btn btn-info comment-btn" href="{% url 'my_app:comment_post' pk=posts.pk %}">Apply</a>
               {% else %}
               <a class="btn btn-info publish-btn" href="{% url 'my_app:publish_post' pk=posts.pk %}">Publish</a>
               {% endif %}
               <div><a href="{% url 'my_app:comment_list' pk=posts.pk%}" >Comments:{{posts.Comment.all.count}}</a></div>
            </div>
          </div>           
           </div>
           {% else %} 
           {% endifequal %}
           {% endfor %}

     <!-- </div> -->
<style type="text/css">
    .card {
        margin: 25px 0;
        opacity: 0.7;
        font-size: 30px;
        font-weight: 400;
    }
    #heading{
        color: white;
    }
</style>
{% endblock %}  